services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=assigment'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'

